# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayane/Pulpit/HexapodPC-robotwalkingwithpad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayane/Pulpit/HexapodPC-robotwalkingwithpad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayane/Pulpit/HexapodPC-robotwalkingwithpad/CMakeFiles /home/ayane/Pulpit/HexapodPC-robotwalkingwithpad/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayane/Pulpit/HexapodPC-robotwalkingwithpad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

src/GUI/gui.o: src/GUI/gui.cpp.o

.PHONY : src/GUI/gui.o

# target to build an object file
src/GUI/gui.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/gui.cpp.o
.PHONY : src/GUI/gui.cpp.o

src/GUI/gui.i: src/GUI/gui.cpp.i

.PHONY : src/GUI/gui.i

# target to preprocess a source file
src/GUI/gui.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/gui.cpp.i
.PHONY : src/GUI/gui.cpp.i

src/GUI/gui.s: src/GUI/gui.cpp.s

.PHONY : src/GUI/gui.s

# target to generate assembly for a file
src/GUI/gui.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/gui.cpp.s
.PHONY : src/GUI/gui.cpp.s

src/GUI/perspectiveprojection.o: src/GUI/perspectiveprojection.cpp.o

.PHONY : src/GUI/perspectiveprojection.o

# target to build an object file
src/GUI/perspectiveprojection.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/perspectiveprojection.cpp.o
.PHONY : src/GUI/perspectiveprojection.cpp.o

src/GUI/perspectiveprojection.i: src/GUI/perspectiveprojection.cpp.i

.PHONY : src/GUI/perspectiveprojection.i

# target to preprocess a source file
src/GUI/perspectiveprojection.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/perspectiveprojection.cpp.i
.PHONY : src/GUI/perspectiveprojection.cpp.i

src/GUI/perspectiveprojection.s: src/GUI/perspectiveprojection.cpp.s

.PHONY : src/GUI/perspectiveprojection.s

# target to generate assembly for a file
src/GUI/perspectiveprojection.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/perspectiveprojection.cpp.s
.PHONY : src/GUI/perspectiveprojection.cpp.s

src/GUI/viewer.o: src/GUI/viewer.cpp.o

.PHONY : src/GUI/viewer.o

# target to build an object file
src/GUI/viewer.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/viewer.cpp.o
.PHONY : src/GUI/viewer.cpp.o

src/GUI/viewer.i: src/GUI/viewer.cpp.i

.PHONY : src/GUI/viewer.i

# target to preprocess a source file
src/GUI/viewer.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/viewer.cpp.i
.PHONY : src/GUI/viewer.cpp.i

src/GUI/viewer.s: src/GUI/viewer.cpp.s

.PHONY : src/GUI/viewer.s

# target to generate assembly for a file
src/GUI/viewer.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/GUI/viewer.cpp.s
.PHONY : src/GUI/viewer.cpp.s

src/Gamepad/gamepad.o: src/Gamepad/gamepad.c.o

.PHONY : src/Gamepad/gamepad.o

# target to build an object file
src/Gamepad/gamepad.c.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Gamepad/gamepad.c.o
.PHONY : src/Gamepad/gamepad.c.o

src/Gamepad/gamepad.i: src/Gamepad/gamepad.c.i

.PHONY : src/Gamepad/gamepad.i

# target to preprocess a source file
src/Gamepad/gamepad.c.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Gamepad/gamepad.c.i
.PHONY : src/Gamepad/gamepad.c.i

src/Gamepad/gamepad.s: src/Gamepad/gamepad.c.s

.PHONY : src/Gamepad/gamepad.s

# target to generate assembly for a file
src/Gamepad/gamepad.c.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Gamepad/gamepad.c.s
.PHONY : src/Gamepad/gamepad.c.s

src/Robot/leg.o: src/Robot/leg.cpp.o

.PHONY : src/Robot/leg.o

# target to build an object file
src/Robot/leg.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/leg.cpp.o
.PHONY : src/Robot/leg.cpp.o

src/Robot/leg.i: src/Robot/leg.cpp.i

.PHONY : src/Robot/leg.i

# target to preprocess a source file
src/Robot/leg.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/leg.cpp.i
.PHONY : src/Robot/leg.cpp.i

src/Robot/leg.s: src/Robot/leg.cpp.s

.PHONY : src/Robot/leg.s

# target to generate assembly for a file
src/Robot/leg.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/leg.cpp.s
.PHONY : src/Robot/leg.cpp.s

src/Robot/robot.o: src/Robot/robot.cpp.o

.PHONY : src/Robot/robot.o

# target to build an object file
src/Robot/robot.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robot.cpp.o
.PHONY : src/Robot/robot.cpp.o

src/Robot/robot.i: src/Robot/robot.cpp.i

.PHONY : src/Robot/robot.i

# target to preprocess a source file
src/Robot/robot.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robot.cpp.i
.PHONY : src/Robot/robot.cpp.i

src/Robot/robot.s: src/Robot/robot.cpp.s

.PHONY : src/Robot/robot.s

# target to generate assembly for a file
src/Robot/robot.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robot.cpp.s
.PHONY : src/Robot/robot.cpp.s

src/Robot/robotcontroler.o: src/Robot/robotcontroler.cpp.o

.PHONY : src/Robot/robotcontroler.o

# target to build an object file
src/Robot/robotcontroler.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotcontroler.cpp.o
.PHONY : src/Robot/robotcontroler.cpp.o

src/Robot/robotcontroler.i: src/Robot/robotcontroler.cpp.i

.PHONY : src/Robot/robotcontroler.i

# target to preprocess a source file
src/Robot/robotcontroler.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotcontroler.cpp.i
.PHONY : src/Robot/robotcontroler.cpp.i

src/Robot/robotcontroler.s: src/Robot/robotcontroler.cpp.s

.PHONY : src/Robot/robotcontroler.s

# target to generate assembly for a file
src/Robot/robotcontroler.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotcontroler.cpp.s
.PHONY : src/Robot/robotcontroler.cpp.s

src/Robot/robotwalk.o: src/Robot/robotwalk.cpp.o

.PHONY : src/Robot/robotwalk.o

# target to build an object file
src/Robot/robotwalk.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotwalk.cpp.o
.PHONY : src/Robot/robotwalk.cpp.o

src/Robot/robotwalk.i: src/Robot/robotwalk.cpp.i

.PHONY : src/Robot/robotwalk.i

# target to preprocess a source file
src/Robot/robotwalk.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotwalk.cpp.i
.PHONY : src/Robot/robotwalk.cpp.i

src/Robot/robotwalk.s: src/Robot/robotwalk.cpp.s

.PHONY : src/Robot/robotwalk.s

# target to generate assembly for a file
src/Robot/robotwalk.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/Robot/robotwalk.cpp.s
.PHONY : src/Robot/robotwalk.cpp.s

src/TCP/tcpacceptor.o: src/TCP/tcpacceptor.cpp.o

.PHONY : src/TCP/tcpacceptor.o

# target to build an object file
src/TCP/tcpacceptor.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpacceptor.cpp.o
.PHONY : src/TCP/tcpacceptor.cpp.o

src/TCP/tcpacceptor.i: src/TCP/tcpacceptor.cpp.i

.PHONY : src/TCP/tcpacceptor.i

# target to preprocess a source file
src/TCP/tcpacceptor.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpacceptor.cpp.i
.PHONY : src/TCP/tcpacceptor.cpp.i

src/TCP/tcpacceptor.s: src/TCP/tcpacceptor.cpp.s

.PHONY : src/TCP/tcpacceptor.s

# target to generate assembly for a file
src/TCP/tcpacceptor.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpacceptor.cpp.s
.PHONY : src/TCP/tcpacceptor.cpp.s

src/TCP/tcpconnector.o: src/TCP/tcpconnector.cpp.o

.PHONY : src/TCP/tcpconnector.o

# target to build an object file
src/TCP/tcpconnector.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpconnector.cpp.o
.PHONY : src/TCP/tcpconnector.cpp.o

src/TCP/tcpconnector.i: src/TCP/tcpconnector.cpp.i

.PHONY : src/TCP/tcpconnector.i

# target to preprocess a source file
src/TCP/tcpconnector.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpconnector.cpp.i
.PHONY : src/TCP/tcpconnector.cpp.i

src/TCP/tcpconnector.s: src/TCP/tcpconnector.cpp.s

.PHONY : src/TCP/tcpconnector.s

# target to generate assembly for a file
src/TCP/tcpconnector.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpconnector.cpp.s
.PHONY : src/TCP/tcpconnector.cpp.s

src/TCP/tcpstream.o: src/TCP/tcpstream.cpp.o

.PHONY : src/TCP/tcpstream.o

# target to build an object file
src/TCP/tcpstream.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpstream.cpp.o
.PHONY : src/TCP/tcpstream.cpp.o

src/TCP/tcpstream.i: src/TCP/tcpstream.cpp.i

.PHONY : src/TCP/tcpstream.i

# target to preprocess a source file
src/TCP/tcpstream.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpstream.cpp.i
.PHONY : src/TCP/tcpstream.cpp.i

src/TCP/tcpstream.s: src/TCP/tcpstream.cpp.s

.PHONY : src/TCP/tcpstream.s

# target to generate assembly for a file
src/TCP/tcpstream.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/TCP/tcpstream.cpp.s
.PHONY : src/TCP/tcpstream.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hex"
	@echo "... src/GUI/gui.o"
	@echo "... src/GUI/gui.i"
	@echo "... src/GUI/gui.s"
	@echo "... src/GUI/perspectiveprojection.o"
	@echo "... src/GUI/perspectiveprojection.i"
	@echo "... src/GUI/perspectiveprojection.s"
	@echo "... src/GUI/viewer.o"
	@echo "... src/GUI/viewer.i"
	@echo "... src/GUI/viewer.s"
	@echo "... src/Gamepad/gamepad.o"
	@echo "... src/Gamepad/gamepad.i"
	@echo "... src/Gamepad/gamepad.s"
	@echo "... src/Robot/leg.o"
	@echo "... src/Robot/leg.i"
	@echo "... src/Robot/leg.s"
	@echo "... src/Robot/robot.o"
	@echo "... src/Robot/robot.i"
	@echo "... src/Robot/robot.s"
	@echo "... src/Robot/robotcontroler.o"
	@echo "... src/Robot/robotcontroler.i"
	@echo "... src/Robot/robotcontroler.s"
	@echo "... src/Robot/robotwalk.o"
	@echo "... src/Robot/robotwalk.i"
	@echo "... src/Robot/robotwalk.s"
	@echo "... src/TCP/tcpacceptor.o"
	@echo "... src/TCP/tcpacceptor.i"
	@echo "... src/TCP/tcpacceptor.s"
	@echo "... src/TCP/tcpconnector.o"
	@echo "... src/TCP/tcpconnector.i"
	@echo "... src/TCP/tcpconnector.s"
	@echo "... src/TCP/tcpstream.o"
	@echo "... src/TCP/tcpstream.i"
	@echo "... src/TCP/tcpstream.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

